# remote_theme: just-the-docs/just-the-docs
url: https://gitee.com/liu_xukang/sage.git
baseurl: /shanhai
title: 钻采工程智能助手
description: 一个强大的问答平台，结合了大模型 RAG 知识库与知识图谱技术，基于 Llamaindex + VueJS + FastAPI + Neo4j 构建。
search_enabled: true
search_full_content: true
aux_links:
  "在 GitHub 上查看":
    - 

# 启用中文支持
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# 设置默认语言
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home
      search_exclude: true